PRINT MACRO MES
MOV AH, 09H
LEA DX, MES
INT 21H
ENDM
.model small
.DATA
MSG1 DB 10,13,"ENTER STR:$"
MSG2 DB 10,13,"REVERSE STR:$"
STR1 DB 25 DUP('$')
REV1 DB 25 DUP('$')
.CODE
START: MOV AX, @DATA
MOV DS, AX
PRINT MSG1
MOV AH, 0AH ; GET STRING
LEA DX, STR1
INT 21H
PRINT MSG2
LEA SI, STR1 ; SI POINTS TO STRING
INC SI ; SKIP LENGTH PART
MOV CH, 00H ;
MOV CL, STR1+1 ; CX=LEN OF STR1
ADD SI, CX ;POINT TO END OF STRING
LEA DI, REV1 ; DI POINTS TO REV1 STRING
MOV DL, STR1+1 ; DL = LENGTH OF STR1
INC DI ; POINT TO LENGTH PART OF REV1
MOV [DI], DL ; COPY LENGTH TO REV1
INC DI ; POINT TO STRING PART OR REV1
BACK: MOV DL, [SI]
MOV [DI], DL
DEC SI

INC DI
DEC CX
JNZ BACK
PRINT REV1+2 ; PRINT RESULT
END1: MOV AH,4CH
INT 21H
END START
